### PR TITLE
Feature/aws config

### PR DESCRIPTION
**Pull request by ppaulis**
give the possibility to read AWS config from the framework

### CODE REVIEW

**Review by Pierozi — APPROVED** [review]
It's Ok but i'm curious about the need of that ?
Create a Factory of SQS for instance the factory of aws.
this add an useless overhead.

**Comment by ppaulis** [comment]
@Pierozi it's for a customer project where I have to inject the AWS credentials from the ZF config. How would you have done it?

**Comment by ppaulis** [comment]
@Pierozi What do you suggest?

**Comment by Pierozi** [comment]
@ppaulis If we need use `SQS` because customer want set this service, by example as a notification.
In this case our queue abstraction is not necessary because the customer want to work with this specific service, parameters and options associate can be relative different than another queue.

I think it's a lot for finally return one line of code below : 

```
$sqs = new Aws\Sqs\SqsClient([
    'version' => 'latest',
    'region'  => 'us-west-2'
    'credentials' => [
        'key'    => 'my-access-key-id',
        'secret' => 'my-secret-access-key',
    ]
]);
```

**Pull request merged**
